apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: {{ .Values.app1.replicaCount }}
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: {{ .Values.app1.image.repository }}
        ports:
        - containerPort: {{ (index .Values.app1.service.ports 0).port }}
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"