image: inf-docker.fh-rosenheim.de/sinfemmakk/cloudcompare:latest

stages:
  - init
  - build
  - test

setVaultEnv:
  stage: init
  script:
    - vlt login

test-variables:
  stage: test
  script:
   - vlt secrets
   - make -f Makefile.ci test
   - vlt run --command="make -f Makefile.ci testEnvSecrets"