image: inf-git.fh-rosenheim.de/sinfemmakk/cloudcompare:latest

stages:
  - init
  - build
  - test

setVaultEnv:
  stage: init
  script:
    - vlt login

test-variables:
  stage: test
  script:
   - vlt secrets