image: inf-docker.fh-rosenheim.de/sinfemmakk/cloudcompare:latest

stages:
  - init
  - build
  - test

setVaultEnv:
  stage: init
  script:
    - vlt login
    - vlt config

testAWSCLI:
  stage: init
  script:
    - aws --version
    - vlt run --command="make -f Makefile.ci checkAwsLggedIn"

deployCamelCaseConverterMavenToRegistry:
  stage: build
  script:
    - cd ./src/camelCase
    - vlt run --command="make -f makefile.ci deployToGitlabPackageRegistry"

test-variables:
  stage: init
  script:
   - vlt secrets
   - make -f Makefile.ci test
   - vlt run --command="make -f Makefile.ci testEnvSecrets"