image: ubuntu

build:
  stage: build
  script:
    - apt update && apt install -y gpg wget lsb-release
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update && apt install vlt
    - echo "Contents of ./bin/build.sh:"
    - cat ./bin/build.sh
    - vlt run --command ./bin/build.sh
