# Use Maven with OpenJDK to build the project
FROM --platform=linux/amd64 maven:3.8.2-openjdk-17-slim as builder


# auth for registry
ARG GIT_GITLAB_TOKEN
ARG GIT_GITLAB_BASE_URL
ARG GIT_GITLAB_CLOUDCOMPARE_ID

# Convert build arguments to environment variables
ENV GIT_GITLAB_TOKEN=$GIT_GITLAB_TOKEN
ENV GIT_GITLAB_BASE_URL=$GIT_GITLAB_BASE_URL
ENV GIT_GITLAB_CLOUDCOMPARE_ID=$GIT_GITLAB_CLOUDCOMPARE_ID

COPY settings.xml /root/.m2/ 
RUN chmod 777 /root/.m2/settings.xml

# Copy your source code
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

# Build the project
RUN mvn clean package -s /root/.m2/settings.xml

# Use Amazon Corretto for the runtime image
FROM amazoncorretto:17

WORKDIR /app

# Copy the built JAR file from the builder stage
COPY --from=builder /usr/src/myapp/target/cammelCaseLambda-1.0-SNAPSHOT.jar /app/cammelCaseLambda.jar

