version: '3.8'
services:
  camel-case-lambda-function:
    build: 
      context: ./
      dockerfile: dockerfile
      args:
        GIT_GITLAB_TOKEN: ${GIT_GITLAB_TOKEN}
        GIT_GITLAB_BASE_URL: ${GIT_GITLAB_BASE_URL}
        GIT_GITLAB_CLOUDCOMPARE_ID: ${GIT_GITLAB_CLOUDCOMPARE_ID}
