
build:
	@vlt run --command="make -f makefile.ci build"
deploy:
	@vlt run --command="make -f makefile.ci deploy"
createRole:
	@vlt run --command="make -f makefile.ci createRole"
test:
	@vlt run --command="make -f makefile.ci test"

.PHONY: build deploy createRole test