# --- Stage 1: Build the application ---
FROM --platform=linux/amd64 maven:3.8.2-openjdk-17-slim AS build

# auth for registry
ARG GIT_GITLAB_TOKEN
ARG GIT_GITLAB_BASE_URL
ARG GIT_GITLAB_CLOUDCOMPARE_ID

# Convert build arguments to environment variables
ENV GIT_GITLAB_TOKEN=$GIT_GITLAB_TOKEN
ENV GIT_GITLAB_BASE_URL=$GIT_GITLAB_BASE_URL
ENV GIT_GITLAB_CLOUDCOMPARE_ID=$GIT_GITLAB_CLOUDCOMPARE_ID


# Set the working directory in the Docker image
WORKDIR /app

# Copy the Maven pom.xml and settings.xml files
COPY pom.xml .
# Copying to the default maven configuration directory
COPY settings.xml /root/.m2/ 
RUN chmod 777 /root/.m2/settings.xml

RUN echo GIT_GITLAB_TOKEN $GIT_GITLAB_TOKEN
RUN echo GIT_GITLAB_BASE_URL $GIT_GITLAB_BASE_URL
RUN echo GIT_GITLAB_CLOUDCOMPARE_ID $GIT_GITLAB_CLOUDCOMPARE_ID

# Download project dependencies
# This layer will only be re-built if the pom.xml changes
RUN mvn dependency:go-offline -s /root/.m2/settings.xml

# Copy the project source files
COPY src src/

# Build the application
RUN mvn clean package

# --- Stage 2: Run the application ---
FROM openjdk:17-slim

# Set the working directory
WORKDIR /app
# Copy the built JAR from the build stage
COPY --from=build /app/target/cloudCompare-0.0.1-SNAPSHOT.jar /app/app.jar

# Set the command to run your application
CMD ["java", "-jar", "/app/app.jar"] 
