version: '3'

services:
  api:
    image: prime-numbers-checker-springboot-app
    build:
      context: ./
      dockerfile: dockerfile
      args:
        GIT_GITLAB_TOKEN: ${GIT_GITLAB_TOKEN}
        GIT_GITLAB_BASE_URL: ${GIT_GITLAB_BASE_URL}
        GIT_GITLAB_CLOUDCOMPARE_ID: ${GIT_GITLAB_CLOUDCOMPARE_ID}
    ports:
      - 8080:8080
