SHELL := /bin/bash

azureLogin:
	@az login --service-principal --username $$AZURE_CLIENT_ID --password $$AZURE_CLIENT_SECRET --tenant $$AZURE_TENANT_ID

buildAzureFunction: azureLogin
	@mvn dependency:go-offline -s ./settings.xml
	@mvn clean package -s ./settings.xml
	@exit

deployAzureFunction:
	@mvn azure-functions:deploy -s ./settings.xml