apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: camelcase-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camelcase-deployment  # Make sure this matches the deployment name of camelCase
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 80
