# @baseUrl = http://localhost
 #@baseUrl = http://localhost:8080
@baseUrl = ecs-alb-55534682.eu-central-1.elb.amazonaws.com
{{baseUrl}}/convertToCamelCase?text=your_text_here
Content-Type: application/json

###

GET {{baseUrl}}/actuator/health
Content-Type: application/json