# @baseUrl = http://localhost
# @baseUrl = http://localhost:8080
@baseUrl = localhost:8080
GET {{baseUrl}}/greeting

###

GET {{baseUrl}}/greeting?name=Jane
Content-Type: application/json

###

GET {{baseUrl}}/actuator/health
Content-Type: application/json