# Starting from a amd Debian Bullseye Slim base image
FROM --platform=linux/amd64 debian:bullseye-slim

# Update and install necessary dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gpg \
    curl \
    lsb-release \
    ca-certificates \
    openssl \
    unzip \
    make

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip

# Cleanup from AWS CLI installation
RUN apt-get purge -y \
    gpg \
    curl \
    lsb-release \
    openssl \
    unzip && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
#check aws still there
RUN aws --version
# Re-update for VLT installation
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    lsb-release \
    gpg \
    ca-certificates

# Install VLT
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && apt-get install -y vlt

# Cleanup after VLT installation
RUN apt-get purge -y \
    curl \
    lsb-release \
    gpg && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
# Test
RUN aws --version && \
    vlt --version
