git:
  gitlab:
    docker:
      base_url: inf-docker.fh-rosenheim.de
    base_url: inf-git.fh-rosenheim.de
    username: sinfemmakk
    tokenName: gitlab_dev
    cloudCompareSecrets: 
      url: https://inf-git.fh-rosenheim.de/sINFemmakk/cloudCompareSecrets.git
    cloudCompare:
      path: /sinfemmakk/cloudcompare
      ID: 11831
aws:
  id: 436888476506
  user: thesis
  DEFAULT_REGION: eu-central-1
  cli:
    region: eu-central-1

azure:
  id: 546be16f-a4d3-4f2b-b085-772077cc6ca5
  CLIENT:
    ID: 07e1c347-135f-40f3-923a-0ef165745bbe
  TENANT:
    ID: b6ef08e4-6287-493d-bd26-e83fc1f75dcf
  Service_Principal:
    app_Id: 6847561c-b805-4a5c-88b5-981254a16f97
    display_Name: azure-cli-2023-10-27-00-27-06
    tenant: b6ef08e4-6287-493d-bd26-e83fc1f75dcf

gcc:
# vault for gitlab: https://developer.hashicorp.com/hcp/docs/vault-secrets/integrations/gitlab
HCP:
  ORGANIZATION: 85f59b75-1b2e-469a-85ae-f179371e81c7
  PROJECT: e87752c4-7fd3-4c40-b719-6e92085100d5


db:
  name: mydb
  username: dbuser

jmeter:
  testConfig:
    duration: 60
    requests: 100
  aws:
    lambda:
      base_url:  "tmp"
      camelcasePath: "tmp"
      checkPrimePath: "tmp"
    ecs:
      base_url:  "tmp"
      camelcasePath: "tmp"
      checkPrimePath: "tmp"
    eks:
      base_url:  "tmp"
      camelcasePath: "tmp"
      checkPrimePath: "tmp"
    beanstalk:
      base_url:  "tmp"
      camelcasePath: "tmp"
      checkPrimePath: "tmp"
    fargate:
      base_url:  "tmp"
      camelcasePath: "tmp"
      checkPrimePath: "tmp"
  azure:
    function:
      base_url:  "tmp"
      camelcasePath: "tmp"
      checkPrimePath: "tmp"
    aks:
      base_url:  "tmp"
      camelcasePath: "tmp"
      checkPrimePath: "tmp"
